spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: smtp.mail.ru
#    port: 587
#    username: testMail@mail.ru
#    password: passApplication
#    properties:
#      mail:
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#server:
#  port: 4455

security:
  jwt:
    secret: "SomeKey"
    tokenExpiration: 3m
    expiration-minutes: 30
    secret-key: bXkgc2VjcmV0IGtleSBhbmQgdSBhcmUgbm9vYiBoYWNrZXI=