version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=skillbox
      - POSTGRES_PASSWORD=skillbox
      - POSTGRES_DB=skillbox
    volumes:
      - ./pg-config:/docker-entrypoint-initdb.d

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: on-failure

  kafka-service:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - kafka:/data
    restart: on-failure

  frontend:
    image: skillboxteam32/front:latest
    ports:
      - "8099:80"
    tty: true
    restart: always
    volumes:
      - ./nginx-config:/etc/nginx/conf.d

  backend:
    image: skillboxteam32/social-media
    environment:
      - DB_USERNAME=skillbox
      - DB_PASSWORD=skillbox
      - DB_HOST=postgres
    tty: true
    restart: on-failure

volumes:
  kafka:

