spring:
  application:
    name: admin-console
app:
  apiPrefix: /api/v1
  gatewayUrl: "http://localhost:9090"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true