spring:
  application:
    name: geo-service
  codec:
    max-in-memory-size: 1048576
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true