spring:
  application:
    name: geo-service
  codec:
    max-in-memory-size: 1048576
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true
management:
  endpoints:
    web:
      base-path: /api/v1/geo/actuator
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
      distribution:
        percentiles-histogram:
          http:
            server:
              requests:
                true
        percentiles:
          http:
            server:
              requests:
                - 0.5
                - 0.9
                - 0.99
server:
  port: 0