spring:
  application:
    name: notification-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/global_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  mandatory-file-encoding: UTF-8

  liquibase:
    change-log: classpath://db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    topic: notifications

app:
  apiPrefix: /api/v1/notifications

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true
management:
  endpoints:
    web:
      base-path: /api/v1/notifications/actuator
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
      distribution:
        percentiles-histogram:
          http:
            server:
              requests:
                true
        percentiles:
          http:
            server:
              requests:
                - 0.5
                - 0.9
                - 0.99
server:
  port: 0