spring:
  application:
    name: user-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/global_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  mandatory-file-encoding: UTF-8

  liquibase:
    change-log: classpath://db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    topic: notifications;audit
  cloud:
    function:
      definition: friendshipEventPublisher;auditEventPublisher
    bindings:
      friendshipEventPublisher-out-0:
        destination: notifications
      auditEventPublisher-out-0:
        destination: audit
  web:
    resources:
      add-mappings: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true

yandex-cloud:
  id-key: YCAJEbjmnRHm7TJgZkPR3RaHq
  secret-key: YCPwGX7Y9t6l-Or0pEQtkoPRYkNPz3a9Pw1UxjPA
  bucket-name: skillbox-social-network-media-bucket
management:
  endpoints:
    web:
      base-path: /api/v1/account/actuator
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
      distribution:
        percentiles-histogram:
          http:
            server:
              requests:
                true
        percentiles:
          http:
            server:
              requests:
                - 0.5
                - 0.9
                - 0.99
server:
  port: 0