spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  mandatory-file-encoding: UTF-8

  liquibase:
    change-log: classpath://db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true

custom:
  rest:
    basePath: /api/v1

server:
  port: 0

