variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository --fail-at-end --show-version"

stages:
  - build
  - test
  - sonarqube-check
  - deploy

cache:
  paths:
    - .m2/repository
  key: "$CI_COMMIT_SHA"

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean compile -DskipTests

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test

sonarqube-check-job:
  stage: sonarqube-check
  dependencies:
    - build-job
    - unit-test-job
  cache:
    key: "${CI_COMMIT_SHA}"
    paths:
      - sonar-scanner/
    policy: pull

  script:
    - echo "Running SonarQube analysis..."
    - mvn verify sonar:sonar
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

deploy-job:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying application..."
    - mvn clean package -DskipTests