version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  psql:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES="user_db","post_db"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
