version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES="user_db","post_db","auth_user_db"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d

  frontend:
    image: skillboxteam32/front:latest
    ports:
      - "8099:80"
    tty: true
    restart: always
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
