services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES="user_db","post_db"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ../frontend/
    image: skillgroup35/frontend
    ports:
      - "8099:8080"
    tty: true
    restart: always
    volumes:
      - ./nginx-config:/etc/nginx/conf.d

  repository:
    build:
      context: ./repository/
    image: nginx
    ports:
      - "80:80"
    tty: true
    restart: always
    volumes:
      - ./repository/nginx-config-repo:/etc/nginx/conf.d
      - .:/usr/share/nginx/html


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/root/redis
      #- ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      #  - REDIS_DATABASES=16
      - REDIS_DATABASES=1
