services:
  discovery:
    build:
      context: ..
      dockerfile: ./discovery/Dockerfile
      args:
      - DIRECTORY=discovery
      no_cache: true
    image: discovery:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always

  authentication:
    build:
      context: ..
      dockerfile: ./authentication/Dockerfile
      args:
        - DIRECTORY=authentication
      no_cache: true
    image: authentication:0.0.1-SNAPSHOT
#    ports:
#      - "8083:8083"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/user_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - FRONT_HOST=http://95.174.93.240
    restart: always
    depends_on:
      - discovery

  post-service:
    build:
      context: ..
      dockerfile: ./post-service/Dockerfile
      args:
        - DIRECTORY=post-service
      no_cache: true
    image: post-service:0.0.1-SNAPSHOT
#    ports:
#      - "8080:8080"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/post_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    restart: always
    depends_on:
      - discovery

  user-service:
    build:
      context: ..
      dockerfile: ./user-service/Dockerfile
      args:
        - DIRECTORY=user-service
      no_cache: true
    image: user-service:0.0.1-SNAPSHOT
#    ports:
#      - "8081:8081"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/user_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    restart: always
    depends_on:
      - discovery

  gateway:
    build:
      context: ..
      dockerfile: ./gateway/Dockerfile
      args:
        - DIRECTORY=gateway
      no_cache: true
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
    restart: always
    depends_on:
      - authentication
      - user-service
      - post-service

  frontend:
    build:
      context: ../frontend/
    image: skillgroup35/frontend
    ports:
      - "8099:8080"
    tty: true
    restart: always
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      - gateway
